[workspace]
resolver = "2"
members = [
    "crates/toku",
]

[workspace.dependencies]
anyhow = "1.0.75"
futures = "0.3.29"
lazy_static = "1.4.0"
tokio = { version = "1", default-features = false, features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "io-std",
    "io-util",
    "fs",
    "tracing",
] }
tracing = "0.1.40"
