[package]
name = "toku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bstr = "1.7.0"

[lib]
name = "toku"
doctest = false
