[package]
name = "ui"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "ui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tracing.workspace = true
ratatui.workspace = true
editor.workspace = true
