[package]
name = "selector"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "selector"
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tore.workspace = true
