[package]
name = "editor"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "editor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow.workspace = true
slotmap.workspace = true
